[tool.isort]
profile = "black"
line_length = 120

[tool.mypy]
check_untyped_defs = true
ignore_missing_imports = true
warn_redundant_casts = true
warn_unused_ignores = true
show_error_context = true
show_column_numbers = true

[tool.blue]
line_length = 120
