from typing import Protocol


class Impossible(Exception):
    pass


class Comparable(Protocol):
    def __lt__[S](self: S, other: S) -> bool: ...
    def __le__[S](self: S, other: S) -> bool: ...
    def __gt__[S](self: S, other: S) -> bool: ...
    def __ge__[S](self: S, other: S) -> bool: ...
